export const TOOL_NAMES = {
  CAMERA: "camera",
  GALLERY: "gallery",
  AUDIO_RECORD: "audio_record",
  SPEECH_OUTPUT: "speech_output",
  CALL: "call",
  CONTACTS: "contacts",
  SHARE: "share",
  LOCATION: "location",
  MAPS: "maps",
  REMINDER: "reminder",
  NOTIFICATION: "notification",
  CALENDAR: "calendar",
  NOTES: "notes",
  FILES: "files",
  WEB_SEARCH: "web_search",
  BROWSER: "browser",
  OPEN_APP: "open_app",
  APP_ALIASES: "app_aliases",
} as const;
